version: '3.8'

services:
  web:
    build: .
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=development
      - DATABASE_URL=postgresql://palace_user:palace_pass@db:5432/palace_of_quests
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      - db
      - redis
    volumes:
      - .:/app
    command: python run.py

  db:
    image: postgres:15
    environment:
      - POSTGRES_DB=palace_of_quests
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=Palace713
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

volumes:
  postgres_data:
